version: '3.4'

services:
  catalog.api:
    container_name: catalog.api
    environment:
      - ConnectionStrings:Default=Server=mssql;Database=Catalog;User Id=sa;Password=P@ssword;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    ports:
      - 8000:80
  
  db:
    container_name: mssql
    environment:
      - SA_PASSWORD=P@ssword
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433